### ISSUE TITLE
Are ALL Detectors expected to be in the output?

### ISSUE THREAD

**Issue by btrautmann** [google/android-lint-performance-probe#3]
When running the probe against my project, I do not see all the `Detector`s listed in the output. Is EVERY `Detector` supposed to be in the list, or does it truncate them if they are way at the bottom? I tested this on a small project where lint failed for a custom rule and even on that run the `Detector` that reported the `Issue` was not in the list. I may be able to put together a small project that can reproduce this, but won't waste the time unless this is a bug. Thank you!

**Comment by gharrma** [comment]
There is no truncation, so any detector that is instantiated should appear in the list.

However, the probe does not automatically pick up custom Lint checks. For custom Lint checks you'll have to add to the set of regular expressions in `LintDetectorStats.java`. Let me know if that works for you!

**Comment by btrautmann** [comment]
Shoot. I had tried that, too, based on this issue: https://github.com/google/android-lint-performance-probe/issues/2, but it wasn't working. Had I read the README more carefully, I would have seen the tip on using the `--no-daemon` flag after re-assembling the probe to ensure the new one is used.

Thank you for your time, sorry for the unnecessary noise!

**Comment by gharrma** [comment]
No worries, thanks for trying out the probe!
