### ISSUE TITLE
Error occurred during initialization of VM Could not find agent library

### ISSUE THREAD

**Issue by panhongjin** [google/android-lint-performance-probe#7]
gradle.properties set org.gradle.jvmargs: 

org.gradle.jvmargs=-agentpath:C:\\Program Files\\YourKit Java Profiler 2021.3-b223\\bin\\win64\\yjpagent.dll=disableall,probebootclasspath=E:\\workspace\\android-lint-performance-probe-master\\build\\libs\\lint-performance-probe.jar,probe_on=com.android.tools.probes.LintDetectorStats

Sync project with gradle files fail, error :

Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.5/userguide/gradle_daemon.html
Process command line: C:\Program Files\Java\jdk1.8.0_191\bin\java.exe -agentpath:C:/Program Files/YourKit Java Profiler 2021.3-b223/bin/win64/yjpagent.dll=disableall,probebootclasspath=E:/workspace/android-lint-performance-probe-master/build/libs/lint-performance-probe.jar,probe_on=com.android.tools.probes.LintDetectorStats -Dfile.encoding=GBK -Duser.country=CN -Duser.language=zh -Duser.variant -cp C:\Users\Administrator\.gradle\wrapper\dists\gradle-6.5-bin\6nifqtx7604sqp1q6g8wikw7p\gradle-6.5\lib\gradle-launcher-6.5.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.5
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not find agent library C:/Program in absolute path, with error: Can't find dependent libraries

-----------------------
Check the JVM arguments defined for the gradle process in:
 - gradle.properties in project root directory

**Comment by gharrma** [comment]
I think you need quotes around the file paths.
Right now it thinks your agent path is just `C:/Program`:
> Could not find agent library C:/Program in absolute path
